version: '2'

services:
    mysql:
        image: mysql
        restart: always
        environment:
           - variables.env
        volumes:
            - ./data/mysql:/docker-entrypoint-initdb.d
    nginx:
        depends_on:
            - phpfpm
        image: nginx
        ports:
            - "80:80"
        restart: always
        working_dir: /var/www
        volumes:
            - ./phanbook:/var/www
            - ./conf/nginx/phanbook.conf:/etc/nginx/conf.d/default.conf
        links:
            - phpfpm
    
    phpfpm:
        image: phalconphp/php-apache:ubuntu-16.04
        restart: always
        working_dir: /var/www
        ports:
            - "8080:80"
        volumes:
            - ./phanbook:/var/www
        links:
            - mysql
        depends_on:
            - mysql

    composer:
        restart: 'no'
        image: phalconphp/composer
        command: install --no-dev
        working_dir: /var/www
        volumes:
            - ./phanbook:/var/www


